import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import Footer from "@/components/Footer";
import { Toaster } from "@/components/ui/toaster";
import { title } from "process";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Pet Adoption",
  description: "Generated by create next app",
};

const localization = {
  signIn: {
    start: {
      title: "Нэвтрэх",
      subtitle: "",
      actionText: "шинэ хэрэглэгч ?",
      actionLink: "бүртгүүлэх",
    },
    password: {
      title: "Нууц үгээ оруулна уу",
      subtitle: "",
      actionLink: "Өөр аргаар нэвтрэнэ үү",
    },
    alternativeMethods: {
      title: "Өөр аргаар нэвтрэх",
      subtitle:
        "Асуудалтай тулгарч байна уу? Та нэвтрэхийн тулд эдгээр аргуудын аль нэгийг ашиглаж болно",
      actionText: "",
      actionLink: "",
    },
    forgotPasswordAlternativeMethods: {
      title: "нууц үг мартсан",
      blockButton__resetPassword: "нууц үг шинэчлэх",
      label__alternativeMethods: "Эсвэл өөр аргаар нэвтэрнэ үү",
    },
    forgotPassword: {
      title: "нууц үг шинэчлэх",
      subtitle_email: "таны имэйл хаяг руу илгээсэн кодыг оруулна уу",
    },
  },
  signUp: {
    start: {
      title: "Бүртгэл үүсгэx",
      subtitle: "",
      actionText: "Have an account?",
      actionLink: "Sign in",
    },
    emailLink: {
      title: "Имэйлээ баталгаажуулна уу",
      subtitle: "",
      formTitle: "Verification link",
      formSubtitle: "Use the verification link sent to your email address",
      resendButton: "дахин илгээх",
      verified: {
        title: "Амжилттай бүртгүүллээ",
      },
      loading: {
        title: "Бүртгүүлж байна...",
      },
      verifiedSwitchTab: {
        title: "Имэйлийг амжилттай баталгаажууллаа",
        subtitle: "Үргэлжлүүлэхийн тулд шинээр нээгдсэн таб руу буцна уу",
        subtitleNewTab: "Үргэлжлүүлэхийн тулд өмнөх таб руу буцна уу",
      },
    },
    emailCode: {
      title: "Verify your email",
      subtitle: "to continue to {{applicationName}}",
      formTitle: "Verification code",
      formSubtitle: "Enter the verification code sent to your email address",
      resendButton: "Didn't receive a code? Resend",
    },
    phoneCode: {
      title: "Verify your phone",
      subtitle: "to continue to {{applicationName}}",
      formTitle: "Verification code",
      formSubtitle: "Enter the verification code sent to your phone number",
      resendButton: "Didn't receive a code? Resend",
    },
    continue: {
      title: "Fill in missing fields",
      subtitle: "to continue to {{applicationName}}",
      actionText: "Have an account?",
      actionLink: "Sign in",
    },
  },
  backButton: "өмнөх хуудаслуу буцах",
  formButtonPrimary: "үргэлжлүүлэх",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider localization={localization}>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Toaster />
          <Header />

          {children}
          <div className="">
            <Footer />
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
